# Generated by Django 6.0.3 on 2026-04-18 17:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='users.organization'),
        ),
        migrations.AddField(
            model_name='pointwastetypes',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pickuppoint'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='point_location_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointwastetypes',
            unique_together={('point', 'waste_type')},
        ),
    ]
