# Generated by Django 6.0.3 on 2026-04-26 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointwastetypes',
            name='not_accepted',
            field=models.TextField(default=1, verbose_name='Не принимается'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointwastetypes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото отхода'),
        ),
        migrations.AddField(
            model_name='pointwastetypes',
            name='preparation',
            field=models.TextField(default=1, verbose_name='Как подготовить к сдаче'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointwastetypes',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_types', to='points.pickuppoint'),
        ),
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='points.pickuppoint', verbose_name='Пункт приёма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('waste_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.pointwastetypes', verbose_name='Тип отхода')),
            ],
            options={
                'verbose_name': 'История сдачи',
                'verbose_name_plural': 'История сдач',
                'ordering': ['-created_at'],
            },
        ),
    ]
