volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgis/postgis:17-3.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  backend:
    image: trussty4/cleandistrict_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: trussty4/cleandistrict_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db

  gateway:
    image: trussty4/cleandistrict_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend