# Generated by Django 6.0.3 on 2026-04-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationnews',
            name='organiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.organization'),
        ),
    ]
