# Generated by Django 6.0.3 on 2026-04-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationnews',
            name='organiation',
        ),
    ]
