# Generated by Django 6.0.3 on 2026-04-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
