# Generated by Django 6.0.3 on 2026-06-05 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Лог модерации', 'verbose_name_plural': 'Логи модерации'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить'), ('block', 'Заблокировать')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='content_type',
            field=models.CharField(choices=[('organization', 'Организация'), ('review', 'Отзыв'), ('news', 'Новость')], max_length=20, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='object_id',
            field=models.CharField(max_length=50, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина'),
        ),
    ]
