# Generated by Django 6.0.3 on 2026-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_moderationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='object_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить')], max_length=20, verbose_name='Действие'),
        ),
    ]
