events {}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream backend {
        server backend:8000;
    }

    upstream frontend {
        server frontend:80;
    }

    server {
        listen 80;

        location /static/ {
            alias /staticfiles/;
        }

        location /media/ {
            alias /media/;
        }

        location /api/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location /admin/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location /swagger/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location /redoc/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location /swagger.yaml/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location / {
            proxy_pass http://frontend;
        }
    }
}