# Generated by Django 6.0.3 on 2026-06-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонёна')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('image', models.ImageField(blank=True, null=True, upload_to='org_news/')),
            ],
            options={
                'verbose_name': 'Новость огранизации',
                'verbose_name_plural': 'Новости огранизации',
            },
        ),
    ]
