# Generated by Django 6.0.3 on 2026-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_organizationnews_organiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationnews',
            name='is_published',
        ),
        migrations.AddField(
            model_name='organizationnews',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
