# Generated by Django 6.0.3 on 2026-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='socials',
            field=models.JSONField(blank=True, default=dict, verbose_name='Социальные сети'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Адрес сайта'),
        ),
    ]
