# Generated by Django 6.0.3 on 2026-06-01 09:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_socials_alter_organization_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
