# Generated by Django 6.0.3 on 2026-06-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organization_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_related_name': 'employee', 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
