# Generated by Django 6.0.3 on 2026-06-18 22:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Местоположение')),
                ('work_schedule', models.TextField(verbose_name='График работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('visits_count', models.IntegerField(default=0, verbose_name='Посещений')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
                ('moderation_status', models.CharField(choices=[('new', 'Новый'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пункт приема',
                'verbose_name_plural': 'Пункты приема',
            },
        ),
        migrations.CreateModel(
            name='PointWasteTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_name', models.CharField(verbose_name='Название отхода')),
                ('waste_type', models.CharField(choices=[('plastic', 'Пластик'), ('glass', 'Стекло'), ('biological', 'Био отходы'), ('metal', 'Металл'), ('paper', 'Бумага'), ('battery', 'Батарейки'), ('cardboard', 'Картон'), ('clothes', 'Одежда'), ('shoes', 'Обувь'), ('trash', 'Мусор')], verbose_name='Тип отхода')),
                ('preparation', models.TextField(verbose_name='Как подготовить к сдаче')),
                ('not_accepted', models.TextField(verbose_name='Не принимается')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото отхода')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('is_actual_price', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуально')),
            ],
            options={
                'verbose_name': 'Приём отхода в пункте',
                'verbose_name_plural': 'Приёмы отходов в пунктах',
            },
        ),
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Проверено'), ('rejected', 'Отклонено')], default='pending')),
            ],
            options={
                'verbose_name': 'История сдачи',
                'verbose_name_plural': 'История сдач',
                'ordering': ['-created_at'],
                'default_related_name': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preparation', models.JSONField(default=list)),
                ('warning', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тип отхода',
                'verbose_name_plural': 'Типы одходов',
            },
        ),
    ]
