# Generated by Django 6.0.3 on 2026-06-18 22:34

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='users.organization'),
        ),
        migrations.AddField(
            model_name='pointwastetypes',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_types', to='points.pickuppoint'),
        ),
        migrations.AddField(
            model_name='submissionhistory',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pickuppoint', verbose_name='Пункт приёма'),
        ),
        migrations.AddField(
            model_name='submissionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='submissionhistory',
            name='waste_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.pointwastetypes', verbose_name='Тип отхода'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='point_location_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointwastetypes',
            unique_together={('point', 'waste_name')},
        ),
    ]
