# Generated by Django 6.0.3 on 2026-04-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_pointwastetypes_not_accepted_pointwastetypes_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='average_rating',
        ),
    ]
