# Generated by Django 6.0.3 on 2026-05-04 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_remove_pickuppoint_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionhistory',
            options={'default_related_name': 'submissions', 'ordering': ['-created_at'], 'verbose_name': 'История сдачи', 'verbose_name_plural': 'История сдач'},
        ),
        migrations.AlterField(
            model_name='submissionhistory',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pickuppoint', verbose_name='Пункт приёма'),
        ),
        migrations.AlterField(
            model_name='submissionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
