# Generated by Django 6.0.3 on 2026-05-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_submissionhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointwastetypes',
            unique_together={('point', 'waste_name')},
        ),
    ]
