# Generated by Django 6.0.3 on 2026-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_alter_pointwastetypes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Проверено'), ('rejected', 'Отклонено')], default='pending'),
        ),
        migrations.AlterField(
            model_name='pointwastetypes',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Пластик'), ('glass', 'Стекло'), ('biological', 'Био отходы'), ('metal', 'Металл'), ('paper', 'Бумага'), ('battery', 'Батарейки'), ('cardboard', 'Картон'), ('clothes', 'Одежда'), ('shoes', 'Обувь'), ('trash', 'Мусор')], verbose_name='Тип отхода'),
        ),
    ]

